package ec.fin.biess.creditos.pq.enumeracion;

/**
 * Enumeracion utilizada
 * 
 * @author hugo.mora
 * @date 13 de may. de 2016
 *
 */
public enum BiessEmergenteEnum {

	APORTACIONES("BIESS_EMERGENTE", "APORTACIONES_PQ"), 
	APORTACIONES_CONSECUTIVAS("BIESS_EMERGENTE", "APORTACIONES_CONSECUTIVAS_PQ"), 
	CAPACIDAD_PAGO("BIESS_EMERGENTE", "CAPACIDAD_PAGO_PQ"), 
	PLAZO_MAXIMO("BIESS_EMERGENTE", "PLAZO_MAXIMO_PQ"), 
	FECHA_MORA_PLANILLA("BIESS_EMERGENTE", "FECHA_VALIDA_MORA_PLANILLA_PQ"), 
	FECHA_MORA_COMPROBANTE("BIESS_EMERGENTE", "FECHA_VALIDA_MORA_COMPROBANTE_PQ"), 
	FECHA_BIESS_EMERGENTE_VIGENCIA("BIESS_EMERGENTE", "FECHA_VIGENCIA_PRODUCTO_PQ"), 
	FECHA_VALIDA_IMP_CONSECUTIVAS_PQ("BIESS_EMERGENTE", "FECHA_VALIDA_IMP_CONSECUTIVAS_PQ"),
	MESES_GRACIA("BIESS_EMERGENTE", "MESES_GRACIA_PQ"),
	PORCENTAJE_GARANTIAS_PQ("BIESS_EMERGENTE","PORCENTAJE_GARANTIAS_PQ"),
	CODIGOS_DIVISIONES_POLITICAS("BIESS_EMERGENTE", "CODIGOS_DIVISIONES_POLITICAS"),
	NUMERO_MEMO_DIVIDENDO("BIESS_EMERGENTE", "NUMERO_MEMO_DIVIDENDO"),
	DIAS_MORA_PUBLICOS("BIESS_MORA_PUBLICOS", "DIAS_MORA"),
	MESES_APORTACIONES_GARANTIZA("BIESS_MORA_PUBLICOS", "MESES_APORTACIONES_GARANTIZA"),
	//EMERGENTE COVID-19
	MONTO_MAX_CREDITO_EMERGENTE("BIESS_EMERGENTE", "MONTO_MAX_CREDITO_PQ"), 
	MONTO_ACUMULADO_PQ("BIESS_EMERGENTE", "MONTO_ACUMULADO_PQ"), 
	MONTO_MAX_DESEMBOLSO_CREDITOS_PQ("BIESS_EMERGENTE", "MONTO_MAX_DESEMBOLSO_CREDITOS_PQ"), 
	
	// Credito Mujer
	FECHA_BIESS_MUJER_VIGENCIA("BIESS_MUJER", "FECHA_VIGENCIA_PRODUCTO_PQ"),
	// Credito Mama
	FECHA_BIESS_MAMA_VIGENCIA("BIESS_MAMA", "FECHA_VIGENCIA_PRODUCTO_PQ"),
	// Credito Papa
	FECHA_BIESS_PAPA_VIGENCIA("BIESS_PAPA", "FECHA_VIGENCIA_PRODUCTO_PQ"),
	// Fechas Bloqueos  PQ
	FECHA_BIESS_PQ_BLOQUEO("BIESS_FDS", "FECHA_BLOQUEO_PRODUCTO_PQ");

	/**
	 * Identificador del parametro
	 */
	private String idParametro;
	/**
	 * Nombre del parametro
	 */
	private String nombreParametro;

	/**
	 * @param idParametro
	 * @param nombreParametro
	 */
	private BiessEmergenteEnum(String idParametro, String nombreParametro) {
		this.idParametro = idParametro;
		this.nombreParametro = nombreParametro;
	}

	// Getters and setters
	public String getIdParametro() {
		return idParametro;
	}

	public String getNombreParametro() {
		return nombreParametro;
	}

}
