package ec.fin.biess.creditos.pq.enumeracion;

/**
 * Enumeracion para consulta de parametros (tabla cre_parametrosbiess_tbl)
 * 
 * @author hugo.mora
 *
 */
public enum ParametrosBiessEnum {

	PRODUCTO_POR_TIPO("PQ_FOCALIZADOS", "PRODUCTO_POR_TIPO"), 
	PRODUCTO_EST_PV("PQ_FOCALIZADOS", "PRODUCTO_EST_PV"), 
	PROVEEDOR_CODIGO_INEC("PQ_FOCALIZADOS", "PROVEEDOR_CODIGO_INEC"), 
	PUNTO_VENTA_CODIGO_INEC("PQ_FOCALIZADOS", "PUNTO_VENTA_CODIGO_INEC"), 
	PROD_PROV_PV("PQ_FOCALIZADOS", "PROD_PROV_PV"),
	PROVEEDOR_ESTADO("PQ_FOCALIZADOS", "PROVEEDOR_ESTADO"),
	PUNTO_VENTA_PROVEEDOR_UBICACION("PQ_FOCALIZADOS", "PUNTO_VENTA_PROVEEDOR"),
	PRODUCTO_POR_CODIGO_MEER("PQ_FOCALIZADOS", "PRODUCTO_POR_CODIGO_MEER"),
	INTENTOS_FALLIDOS_OTP("PQ_FOCALIZADOS", "INTENTOS_FALLIDOS_OTP"),
	DIAS_CADUCIDAD("PQ_FOCALIZADOS", "DIAS_CADUCIDAD"),
	PROVEEDOR_POR_CODIGO_MEER("PQ_FOCALIZADOS", "PROVEEDOR_POR_CODIGO_MEER"),
	PUNTO_VENTA_POR_CODIGO_MEER("PQ_FOCALIZADOS", "PUNTO_VENTA_POR_CODIGO_MEER"),
	GENERAR_OTP("BIESS_OTP", "GENERAR_OTP"),
	VALIDAR_OTP("BIESS_OTP", "VALIDAR_OTP"),
	CODIGO_ACTIVACION_FOCALIZADOS("PQ_FOCALIZADOS", "CODIGO_ACTIVACION"),
	MAXIMO_CREDITOS_VIGENTES("PQ_FOCALIZADOS", "MAXIMO_CREDITOS_VIGENTES"),
	TIEMPO_VIGENCIA_OTP("BIESS_OTP", "TIEMPO_VIGENCIA"),
	LONGITUD_OTP("BIESS_OTP", "LONGITUD"),
	URL_CATALOGO_MEER("PQ_FOCALIZADOS", "URL_CATALOGO_MEER"),
	PRODUCTO_EST_TIP_CODPROD("PQ_FOCALIZADOS", "PRODUCTO_EST_TIP_CODPROD"),
	PRODUCTO_EST_TIP("PQ_FOCALIZADOS", "PRODUCTO_EST_TIP"),
	MOSTRAR_CATALOGO("PQ_FOCALIZADOS", "MOSTRAR_CATALOGO"),
	FECHA_VIG_BENEFICIARIO("PARAMETRIZACION_PQ", "FECHA_VIG_BENEFICIARIO"),
	RUC_COMPROBANTE_LIQUIDACION("PARAMETRIZACION_PQ", "RUC_COMPROBANTE_LIQUIDACION"),
	CONSULTAR_RESERVA("PQ_TURISMO", "CONSULTAR_RESERVA"),
	ANULAR_RESERVA("PQ_TURISMO", "ANULAR_RESERVA"),
	MORA_PATRONAL("TIME_OUT", "MORA-PATRONAL"),
	CONSULTA_CONTRATO_PROV("PQ_DINAMICO", "CONSULTA_CONTRATO_PROV"),
	CONSULTA_DATA_PRODUCTO("PQ_DINAMICO", "CONSULTA_DATA_PRODUCTO"),
	NOTIFICAR_PROVEEDOR("PQ_DINAMICO", "NOTIFICA_PROVEEDOR"),
	CONSULTA_DOC_CONTRATO("PQ_DINAMICO", "CONSULTA_DOC_CONTRATO"),
	VALIDA_CESANTIA("PARAMETRIZACION_PQ","VALIDA_CESANTIA");

	private ParametrosBiessEnum(String idParametro, String nombreParametro) {
		this.idParametro = idParametro;
		this.nombreParametro = nombreParametro;
	}

	private String idParametro;

	private String nombreParametro;

	// Getters and setters
	public String getIdParametro() {
		return idParametro;
	}

	public String getNombreParametro() {
		return nombreParametro;
	}

}
